[project]
name = "dzidzo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "boto3>=1.43.108",
    "fastapi[standard]>=0.141.1",
    "pillow>=12.3.0",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.15.1",
    "sqlalchemy[asyncio]>=2.1.1",
]
